/*
Categories of AI Usage:
  Grammar and Style Correction
    Tools: Grammarly, Hemingway
    Purpose: To correct grammatical errors, improve sentence structure, and enhance overall writing style.

  Translation and Language Enhancement
    Tools: DeepL, Google Translate
    Purpose: To translate texts or improve the quality and fluency of the writing in a different language.

  Content Generation and Idea Expansion
    Tools: ChatGPT, OpenAI Codex
    Purpose: To generate initial drafts, expand on ideas, provide suggestions for content, and offer examples.

  Coding Assistance
    Tools: GitHub Copilot
    Purpose: To help with coding tasks, generate code snippets, and provide programming solutions and explanations.

  Citation Assistance
    Tools: Citation Machine
    Purpose: To assist in proper citation formatting.
  
  Data Analysis and Visualization
    Tools: MATLAB, Python libraries (e.g., pandas, matplotlib), e.g. with ChatGPT or DataSpell
    Purpose: To assist in analyzing data sets, generating graphs, and visualizing data.

What You Need to Do
  - Use AI Tools Wisely: Feel encouraged to use AI tools for grammar correction, translation, content generation, coding assistance, plagiarism detection, data analysis and more, but make sure that you have the competencies to judge about the correctness and integrity of the generated content. You are responsible for the output!
  - Be Transparent: Include a short paragraph at the end of your proposal, thesis, seminar paper, project report, or any other text that is assessed describing how you used AI. Specify which tools you used, how extensively, for what purposes, and in which sections of your work you have used them.
  - Review: Make sure you review all text generated by AI tools and mention this as part of the transparency statement
*/

In the process of writing this proposal, I utilized AI tools to enhance efficiency and accuracy. I used ChatGPT to generate ideas and gain insights into domain-specific knowledge that I was unfamiliar with. Additionally, I employed Google Translate to translate academic papers into my native language, allowing for a deeper and faster understanding of the content. I used Better BibTeX to generate references for my bibliography, and Grammarly to correct spelling errors and improve grammar and sentence structure. All AI-generated or AI-assisted content was carefully reviewed and revised to ensure accuracy, coherence, and academic integrity.

